### ISSUE TITLE
It does not work on zoomed pages

### ISSUE THREAD

**Issue by ankit814** [ysun62/Disable-Scrolling-Extension#1]

**Comment by ysun62** [comment]
Hi, it works when I tried on zoomed pages. Did you make sure to refresh all the pre-existing tabs after installation. If yes, and it still doesn't work, could you kindly provide me a short video demo please?

**Comment by ankit814** [comment]
Hi,

Earlier, I tried the extension on pinch zoomed in pages. The extension is not working for the same.
Although, the extension is working perfectly fine when I zoom in using ⌘ and + This resolves my issue.

Thanks
